//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class College_Students
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public System.DateTime Birthday_date { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string House_Address { get; set; }
        public string College_Name { get; set; }
        public Nullable<int> Generation_of_Student { get; set; }
    }
}
