//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_BusinessObjectModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeStudents : Student
    {
        public Nullable<int> Generation_of_Student { get; set; }
        public string College_Name { get; set; }
    }
}
