//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_BusinessObjectModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolStudent : Student
    {
        public string School_Name { get; set; }
        public Nullable<System.DateTime> Enrollment_Date { get; set; }
    }
}
