//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXFromDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcAppHelloWorldEntities2 : DbContext
    {
        public MvcAppHelloWorldEntities2()
            : base("name=MvcAppHelloWorldEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<College_Students> College_Students { get; set; }
        public virtual DbSet<High_School_Students> High_School_Students { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
